const gulp = require('gulp');
const babel = require('gulp-babel');
const sourcemaps = require('gulp-sourcemaps');
const jsonminify = require('gulp-jsonminify');
const rename = require('gulp-rename');
const htmlmin = require('gulp-htmlmin');
const imagemin = require('gulp-imagemin');
const del = require('del');
const gulpif = require('gulp-if');
const uglify = require('gulp-uglify');
const postcss = require('gulp-postcss');
const cssnano = require('cssnano');

const isProd = () => process.env.NODE_ENV === 'production';

gulp.task('js', () => gulp.src(['src/**/*.js'])
  .pipe(gulpif(!isProd, sourcemaps.init()))
  .pipe(babel())
  .pipe(gulpif(isProd, uglify()))
  .pipe(gulpif(!isProd, sourcemaps.write('.')))
  .pipe(gulp.dest('dist'))
);

gulp.task('wxml', () => gulp.src(['src/**/*.{wxml,xml,html}'])
  .pipe(gulpif(isProd, htmlmin({
    collapseWhitespace: true,
    includeAutoGeneratedTags: false,
    keepClosingSlash: true,
    removeComments: true,
    removeEmptyAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
  })))
  .pipe(rename({ extname: '.wxml' }))
  .pipe(gulp.dest('dist'))
);

gulp.task('wxss', () => gulp.src(['src/**/*.{wxss,css}'])
  .pipe(gulpif(isProd, postcss([cssnano()])))
  .pipe(rename({ extname: '.wxss' }))
  .pipe(gulp.dest('dist'))
);

gulp.task('json', () => gulp.src(['src/**/*.json'])
  .pipe(gulpif(isProd, jsonminify()))
  .pipe(gulp.dest('dist'))
);

gulp.task('image', () => gulp.src(['src/**/*.{jpg,jpeg,png,gif,svg}'])
  .pipe(gulpif(isProd, imagemin()))
  .pipe(gulp.dest('dist'))
);

gulp.task('extras', () => gulp.src(['src/**/*.*', '!src/**/*.{js,wxml,xml,html,wxss,json,css,jpg,jpeg,png,gif,svg}'])
  .pipe(gulp.dest('dist'))
);

gulp.task('clean', () => del(['dist/*']));

gulp.task('build', gulp.series('clean', gulp.parallel('js', 'wxml', 'wxss', 'json', 'image', 'extras')));

gulp.task('watch', gulp.series('build', () => {
  gulp.watch('src/**/*.js', gulp.series('js'));
  gulp.watch('src/**/*.{wxml,xml,html}', gulp.series('wxml'));
  gulp.watch('src/**/*.{wxss,css}', gulp.series('wxss'));
  gulp.watch('src/**/*.json', gulp.series('json'));
  gulp.watch('src/**/*.{jpg,jpeg,png,gif,svg}', gulp.series('image'));
  gulp.watch(['src/**/*.*', '!src/**/*.{js,wxml,xml,html,wxss,json,css,jpg,jpeg,png,gif,svg}'], gulp.series('extras'));
}));

gulp.task('default', gulp.series('watch'));
